<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tagclouds_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.tagclouds':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tagclouds offers dynamic urls.') . '</p>';
      $output .= '<p>' . t('Visit example.com/tagclouds/list/2,1,5 to get the vocabularies 2,1 and 5 listed as tag groups.') . '</p>';
      $output .= '<p>' . t('Visit example.com/tagclouds/chunk/2,1,5 to get a tag cloud of the terms in the vocabularies 2,1 and 5.') . '</p>';
      $output .= '<p>' . t(' Note that we limit to five vocabularies.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function tagclouds_theme() {
  return [
    'tagclouds_list_box' => [
      'variables' => [
        'vocabulary' => NULL,
        'children' => NULL
      ]
    ],
    'tagclouds_weighted' => [
      'variables' => [
        'terms' => [],
        'children' => NULL
      ]
    ]
  ];
}

/**
 * Get localized term description unfiltered.
 * Adapted from i18n_taxonomy_term_name(). Should moved to i18n, issue http://drupal.org/node/1704658.
 */
function tagclouds_i18n_taxonomy_term_description($term, $langcode = NULL) {
  return i18n_taxonomy_vocabulary_mode($term->vid, I18N_MODE_LOCALIZE) ? i18n_string(array('taxonomy', 'term', $term->tid, 'description'), $term->description, array('langcode' => $langcode, 'sanitize' => FALSE)) : $term->description;
}

/**
 * Get localized vocabulary description.
 * Adapted from i18n_taxonomy_vocabulary_name(). Should moved to i18n, issue http://drupal.org/node/1704658.
 */
function tagclouds_i18n_taxonomy_vocabulary_description($vocabulary, $langcode = NULL) {
  return i18n_object_langcode($vocabulary) ? $vocabulary->description : i18n_string(array('taxonomy', 'vocabulary', $vocabulary->vid, 'description'), $vocabulary->description, array('langcode' => $langcode));
}
